import express from 'express';
const router = express.Router();
import auth from '../middleware/auth.js';
import LossReport from '../models/LossReport.js';
import StorageFacility from '../models/StorageFacility.js';
import TransportVehicle from '../models/TransportVehicle.js';
import PDFDocument from 'pdfkit';

router.get('/generate', auth, async (req, res) => {
  try {
    const officer = req.officer;

    // 1. Fetch real loss data for this officer
    const lossReports = await LossReport.find({ officer: officer.id });

    const totalLoss = lossReports.reduce((sum, r) => sum + r.quantityLost, 0);
    const totalReports = lossReports.length;

    // 2. Calculate most common cause (fixed – no undefined 'stats')
    const causeCount = lossReports.reduce((acc, r) => {
      acc[r.cause] = (acc[r.cause] || 0) + 1;
      return acc;
    }, {});
    const mostCommonCause = Object.keys(causeCount).reduce((a, b) =>
      causeCount[a] > causeCount[b] ? a : b, 'None'
    );

    // 3. Fetch storage & transport data
    const facilities = await StorageFacility.find({ officer: officer.id });
    const totalCapacity = facilities.reduce((sum, f) => sum + f.capacity, 0);
    const totalAllocated = facilities.reduce((sum, f) => sum + f.allocated, 0);
    const utilization = totalCapacity > 0 ? Math.round((totalAllocated / totalCapacity) * 100) : 0;

    const vehicles = await TransportVehicle.find({ officer: officer.id });
    const totalVehicles = vehicles.length;

    // 4. Create PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="Agriscope_Report.pdf"');

    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('Agriscope Report', { align: 'center' });
    doc.fontSize(12).text(`Generated for: ${officer.fullName || officer.username}`, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    // Executive Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Executive Summary');
    doc.fontSize(11).font('Helvetica').moveDown(0.5);
    doc.text(
      'This report summarizes your agricultural records, including loss analysis, storage/transport status, and recommendations to manage tomato oversupply and reduce waste.',
      { align: 'justify' }
    );
    doc.moveDown(1.5);

    // Production Overview (static placeholder – add real data later if needed)
    doc.fontSize(14).font('Helvetica-Bold').text('Production Overview');
    doc.fontSize(11).moveDown(0.5);
    doc.text('• Average Monthly Production: 4,783 tons (placeholder)');
    doc.text('• Year-over-Year Growth: +12% (placeholder)');
    doc.text('• Peak Production Month: June – August (placeholder)');
    doc.moveDown(1.5);

    // Loss Analysis (now uses real calculated values)
    doc.fontSize(14).font('Helvetica-Bold').text('Loss Analysis');
    doc.fontSize(11).moveDown(0.5);
    doc.text(`• Total Loss Reports: ${totalReports}`);
    doc.text(`• Total Quantity Lost: ${totalLoss.toLocaleString()} tons`);
    doc.text(`• Most Common Cause: ${mostCommonCause}`);
    doc.moveDown(1.5);

    // Storage & Transport (real data)
    doc.fontSize(14).font('Helvetica-Bold').text('Storage & Transport Status');
    doc.fontSize(11).moveDown(0.5);
    doc.text(`• Total Storage Capacity: ${totalCapacity.toLocaleString()} tons`);
    doc.text(`• Current Utilization: ${utilization}%`);
    doc.text(`• Active Transport Vehicles: ${totalVehicles}`);
    doc.moveDown(1.5);

    // Recommendations
    doc.fontSize(14).font('Helvetica-Bold').text('Recommendations');
    doc.fontSize(11).moveDown(0.5);
    doc.text('1. Increase weather monitoring during monsoon season to reduce flood-related losses.');
    doc.text('2. Optimize planting schedules to avoid peak oversupply periods.');
    doc.text('3. Improve storage allocation in high-production districts.');
    doc.text('4. Enhance transport readiness during peak harvest months.');

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    doc.fontSize(10).text(
      `Generated by Agriscope - Confidential • Page 1 of ${pageCount}`,
      50,
      doc.page.height - 50,
      { align: 'center' }
    );

    doc.end();
  } catch (err) {
    console.error('Report generation error:', err);
    // Send error response only if headers not already sent
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate report' });
    }
  }
});

export default router;